apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespaces }}
  name: {{ include "frontend-api-helm.name" . }}-deployement
  labels:
    {{- include "frontend-api-helm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "frontend-api-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "frontend-api-helm.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - name: frontendport
            containerPort: {{ .Values.service.port }}
            protocol: TCP
          env:
          - name: SALARY_URL
            valueFrom:
              configMapKeyRef:
                name: "{{ include "frontend-api-helm.name" . }}-configmap"
                key: "salary-url"
          - name: EMPLOYEE_URL
            valueFrom:
              configMapKeyRef:
                name: "{{ include "frontend-api-helm.name" . }}-configmap"
                key: "employee-url"

